version: '3.9'

services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:15.1
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PW}
  #     - POSTGRES_DB=postgres #optional (specify default database instead of $POSTGRES_DB)
  #   ports:
  #     - "5434:5432"
  #   restart: always

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:6.14
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  #   ports:
  #     - "5050:80"
  #   restart: always

  mysql:
    image: mysql:8.0.31
    container_name: radioschool_mysql
    volumes:
      - radiosch-mysql-data:/var/lib/mysql
    environment:
      # - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    restart: always

volumes:
  radiosch-mysql-data: