openapi: 3.0.3
info:
  title: "Radio School Backend API"
  description: "Radio School Bacakend API"
  version: "1.0.0"
  contact:
    name: "Tectitan"
    email: "dexter_daniel@outlook.com"

servers:
  - url: /api/1.0
    description: Dev Server
  - url: /uat/api/1.0
    description: UAT Server

paths:
  /generate-access-code:
    get:
      operationId: "backend_app.public_web.access_code_apis.generate_access_code"
      tags:
        - "Access Code"
      summary: "Generate access for accessing the Radio School public web"
      responses:
        "200":
          description: "Access Code"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_code:
                    type: string
                    example: 1ERY09


  /fetch-access-code:
      get:
        operationId: "backend_app.public_web.access_code_apis.get_all_access_token"
        tags:
          - "Access Code"
        summary: Fetches all access codes from the Radio School database"
        responses:
          "200":
            description: "Access Code"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    access_code:
                      type: string
                      example: 1ERY09

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
  parameters:
    lname:
      name: "lname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"