openapi: 3.0.0
info:
  title: "Radio School Backend API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api/1.0"

paths:
  /people:
    get:
      operationId: "app.public_web.people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
  parameters:
    lname:
      name: "lname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"